name: Run Jakarta Data TCK

on:
  schedule:
    - cron: '0 0 * * 1,3,5' #Monday, Wednesday, Friday at Midnight

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          java-version: [17, 21]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
          cache: maven
      - name: Test with maven
        run: mvn test -Djakarta.tck.profile=standalone --file tck-runner/pom.xml
